### ISSUE TITLE
Change HTML to Jade

### ISSUE THREAD

**Issue by Revod** [kreativgebiet/kickup#17]
Hi, I want to edit the ```markup.js``` to change the html to jade using [gulp-jade](https://www.npmjs.com/package/gulp-jade) what is the best way to change? in my past, my gulpfile.js are like this: [My gulpfile](https://gist.github.com/Revod/8b8a742269094c9d7198)

where the jade are:
```javascript
var gulp = require('gulp'),
    plumber = require('gulp-plumber'),
    postcss = require('gulp-postcss'),
    autoprefixer = require('autoprefixer'),
    sass = require('gulp-sass'),
    jade = require('gulp-jade'),
    browserSync = require('browser-sync').create();

gulp.task('jade', function () {
    return gulp.src('./jade/*.jade')
        .pipe(plumber())
        .pipe(jade({
            pretty: true
        }))
        .pipe(gulp.dest('./'))
        .on('end', browserSync.reload);
});
```

and I Don't know how to change the html to jade in your Kickup...

Thanks and thanks for this amazing Boilerplate

**Comment by iDuuck** [comment]
After Line 41 of `tasks/markup.js`, please just add `.pipe(jade())`. But also be sure to import `gulp-jade` on the top using `import jade from 'gulp-jade';`.

Should work like this.

**Comment by Revod** [comment]
thanks @iDuuck, and
```javascript
gulp.task('markup', ['sprites'], () => {
  const spriteTransform = (filePath, file) => {
    return file.contents.toString();
  };

  const mainPath = join(src, 'html', '**/*.html');
  const includesPath = join('!.', src, 'html', 'includes', '**/*.html');
  const manifest = gulp.src(join(dest, '..', 'rev-manifest.json'));
```
change the  join(src, 'html', '**/*.html'); to the jade directory?

**Comment by iDuuck** [comment]
oh, yeah. sorry forgot that this should also be changed. is it working for you?

**Comment by Revod** [comment]
@iDuuck  Yeah, work fine but when I run "gulp" and edit the jade file doesn't watch and reload the browser with the changes

**Comment by Revod** [comment]
Done, edit the default.js
