### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [kreativgebiet/kickup#22]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by iDuuck** [comment]
Is this hindering a development without flow? If _no_ then go for it, please :)

**Comment by amilajack** [comment]
Closing, as the PR for this was just made
