### ISSUE TITLE
RFC: Migrate to npm scripts from gulp

### ISSUE THREAD

**Issue by amilajack** [kreativgebiet/kickup#25]
Thoughts on this?

**Comment by iDuuck** [comment]
How would you go for this? I am open to this.

**Comment by amilajack** [comment]
It should be pretty straight forward. Almost anything that can be done with gulp can be done with npm scripts

**Comment by iDuuck** [comment]
Any reason you closed this?
*Anyway:* Go for it in a PR :)

**Comment by amilajack** [comment]
I looked at the work needed for the migration and it seemed like a rewrite was required.

**Comment by iDuuck** [comment]
Would be great. But from scratch is a little hard way to do so. But if this works out, let me know :)
